### ISSUE TITLE
How to restart hasura docker with new parameters?

### ISSUE THREAD

**Issue by yevyevyev** [antstackio/hasura-ecs-aurora-serverless-template#2]
Hello, thanks for the script, I'm wondering how to start the hasura docker with different parameters (e.g. a jwt config) without rebuilding the whole stack? Is there a best practice also how to store the jwt config secret to not hardcode it on the machine?

**Comment by vishwasnavadak** [comment]
Hasura suggests to put configs like jwt config, admin secrets as part of the hasura docker param or environment variables. To discuss about best practices and get more clarity, you can reach out to Hasura discord -> https://discordapp.com/invite/hasura

Hope that helps
