### ISSUE TITLE
Whats the best way to extend the current YML stack?

### ISSUE THREAD

**Issue by rnjailamba** [antstackio/hasura-ecs-aurora-serverless-template#3]
We are using the stack's cloudformation as is to start. 
How can we start using a current resource for example an existing Aurora database.
Also how should we link AWS cognito to the stack as well as lambda functions by extending this template in order to maintain 100% infrastructure as code. 
Thank you and amazing work with the template! @vishwasnavadak

**Comment by vishwasnavadak** [comment]
You can always download the existing cloudformation and edit them for your needs like cognito

For referring to existing aurora serverless, you can remove the Aurora create steps from the template and deploy this stack in the sams VPC as the existing one and replace HASURA_GRAPHQL_DATABASE_URL on the template with existing connection string.

**Comment by rnjailamba** [comment]
Thanks @vishwasnavadak !
