### ISSUE TITLE
Developing on localhost and deploying to the created stack

### ISSUE THREAD

**Issue by rnjailamba** [antstackio/hasura-ecs-aurora-serverless-template#4]
Are there any resources on developing on localhost and then deploying to the created stack @vishwasnavadak

**Comment by vishwasnavadak** [comment]
Since Cloudformation is specific to AWS,  I don't think there is a way to run the templates just locally. we could validate them through aws cli. 
https://docs.aws.amazon.com/cli/latest/reference/cloudformation/index.html

**Comment by rnjailamba** [comment]
Sure, will use that to validate the stack. Thanks again @vishwasnavadak
